# Generated by Django 2.0.6 on 2019-08-16 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapis',
            name='datezapis',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
