# Generated by Django 2.0.6 on 2019-08-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0002_zapis_datezapis'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='photo',
            field=models.ImageField(default=1, upload_to='media', verbose_name='Ваше изображение'),
            preserve_default=False,
        ),
    ]
