# Generated by Django 2.0.6 on 2019-08-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0003_master_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/', verbose_name='Ваше изображение'),
        ),
        migrations.AddField(
            model_name='master',
            name='spec',
            field=models.ManyToManyField(to='zapis.Spec'),
        ),
    ]
