# Generated by Django 2.0.6 on 2019-08-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0004_auto_20190823_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapis',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
