# Generated by Django 2.0.6 on 2019-08-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0005_zapis_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapis',
            name='datezapis',
            field=models.DateField(),
        ),
    ]
