# Generated by Django 2.0.6 on 2019-08-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0006_auto_20190828_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapis',
            name='datezapis',
            field=models.DateField(blank=True, null=True),
        ),
    ]
