# Generated by Django 2.0.6 on 2019-09-06 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0008_workday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datestart', models.DateField(blank=True, null=True)),
                ('dateend', models.DateField(blank=True, null=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapis.Master')),
            ],
        ),
    ]
