# Generated by Django 2.1.3 on 2019-09-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0009_vacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='spec',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spec',
            name='time',
            field=models.CharField(default='1 час', max_length=10),
        ),
    ]
