# Generated by Django 2.0.6 on 2019-09-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0011_master_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='file',
        ),
    ]
