# Generated by Django 2.0.6 on 2019-09-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0013_auto_20190918_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.ImageField(upload_to='photo/'),
        ),
    ]
