# Generated by Django 2.0.6 on 2019-09-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0014_auto_20190918_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/', verbose_name='Ваше изображение'),
        ),
    ]
