# Generated by Django 2.0.6 on 2019-09-27 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0018_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='firma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zapis.Firma'),
            preserve_default=False,
        ),
    ]
