# Generated by Django 2.0.6 on 2019-09-27 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0019_client_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='firma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zapis.Firma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sms',
            name='firma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zapis.Firma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spec',
            name='firma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zapis.Firma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacation',
            name='firma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zapis.Firma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workcalendar',
            name='firma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zapis.Firma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workday',
            name='firma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zapis.Firma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zapis',
            name='firma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zapis.Firma'),
            preserve_default=False,
        ),
    ]
