# Generated by Django 2.0.6 on 2019-10-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0022_firma_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='adress',
        ),
        migrations.AddField(
            model_name='firma',
            name='adress',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
