# Generated by Django 2.0.6 on 2019-10-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0023_auto_20191011_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fio',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
