# Generated by Django 2.0.6 on 2019-10-17 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0024_userprofile_fio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(max_length=100)),
                ('summa', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapis.Firma')),
            ],
        ),
    ]
