# Generated by Django 2.0.6 on 2019-10-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0025_accounting'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='datesms',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firma',
            name='datetarif',
            field=models.DateField(blank=True, null=True),
        ),
    ]
