# Generated by Django 2.0.6 on 2019-11-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0028_auto_20191101_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='balans',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
