# Generated by Django 2.0.6 on 2019-11-01 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0029_firma_balans'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zapis.Client'),
            preserve_default=False,
        ),
    ]
