# Generated by Django 2.0.6 on 2019-12-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0030_log_client'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='zapis',
            index=models.Index(fields=['firma', 'begin', 'master', 'datezapis', 'status'], name='zapis_zapis_firma_i_23b48c_idx'),
        ),
    ]
