# Generated by Django 2.0.6 on 2019-12-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0031_auto_20191201_1056'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['firma', 'id'], name='zapis_clien_firma_i_479918_idx'),
        ),
        migrations.AddIndex(
            model_name='master',
            index=models.Index(fields=['firma'], name='zapis_maste_firma_i_5d7910_idx'),
        ),
        migrations.AddIndex(
            model_name='workcalendar',
            index=models.Index(fields=['firma'], name='zapis_workc_firma_i_764ec1_idx'),
        ),
        migrations.AddIndex(
            model_name='workday',
            index=models.Index(fields=['firma', 'master', 'nomday'], name='zapis_workd_firma_i_5bc8f4_idx'),
        ),
    ]
