# Generated by Django 2.0.6 on 2019-12-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0032_auto_20191201_1100'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='zapis',
            index=models.Index(fields=['firma', 'datezapis'], name='zapis_zapis_firma_i_b99922_idx'),
        ),
    ]
