# Generated by Django 2.0.6 on 2020-01-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0033_auto_20191201_1104'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='master',
            index=models.Index(fields=['firma', 'id'], name='zapis_maste_firma_i_be3f19_idx'),
        ),
    ]
