# Generated by Django 2.0.6 on 2020-01-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0034_auto_20200125_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='booklink',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
