# Generated by Django 2.0.6 on 2020-02-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0035_firma_booklink'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timeoffset',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='', max_length=30),
        ),
    ]
