# Generated by Django 2.0.6 on 2020-02-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0036_auto_20200208_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='timeoffset',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='firma',
            name='timezone',
            field=models.CharField(default='', max_length=30),
        ),
    ]
