# Generated by Django 2.0.6 on 2020-02-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0037_auto_20200208_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='timezone_text',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='firma',
            name='timezone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
